apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: distributed-job-queue
type: Opaque
stringData:
  host: "http://rabbitmq.distributed-job-queue.svc.cluster.local:15672"
  username: "admin"
  password: "admin"
