x-service-defaults: &service-defaults
  restart: always
  networks:
    - app-network

x-common-env: &common-env
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_queue_db
  SPRING_REDIS_HOST: redis_queue

services:
  nginx:
    <<: *service-defaults
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - producer
    networks:
      - app-network

  producer:
    <<: *service-defaults
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      SERVER_PORT: 8080
    volumes:
      - ./docs/logs:/logs
    deploy:
      replicas: 3

  worker:
    <<: *service-defaults
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      <<: *common-env
      SERVER_PORT: 8085
    volumes:
      - ./docs/logs:/logs
    deploy:
      replicas: 5

networks:
  app-network:
    external: true
