events {
    worker_connections 1024;
}

http {
    upstream producer_cluster {
        server producer:8080;
    }

    upstream worker_cluster {
        server worker:8085;
    }

    server {
        listen 80;

        location /worker/ {
            proxy_pass http://worker_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /producer/ {
            proxy_pass http://producer_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
