apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # --- Namespace ---
  - namespace.yaml

  # --- Elasticsearch ---
  - elasticsearch/statefulset-elasticsearch.yaml
  - elasticsearch/service-elasticsearch.yaml

  # --- Fluent Bit ---
  - fluentbit/daemonset-fluentbit.yaml
  - fluentbit/configmap-fluentbit.yaml
  - fluentbit/rbac-fluentbit.yaml

  # --- Kibana ---
  - kibana/deployment-kibana.yaml
  - kibana/service-kibana.yaml
  - kibana/ingress-kibana.yaml
