spring:
  main:
    web-application-type: none
  application:
    name: worker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.49.2:30432/appdb?prepareThreshold=0}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:apppass}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:300000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:600000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      keepalive-time: ${HIKARI_KEEPALIVE_TIME:120000}
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.49.2}
    port: ${RABBITMQ_PORT:30672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: false
    template:
      mandatory: true
    publisher-confirm-type: correlated
  threads:
    virtual:
      enabled: true

schedule:
  cron:
    consume: "*/10 * * * * *"

app:
  rabbitmq:
    startup-check:
      enabled: true


logging:
  level:
    root: INFO
