apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: distributed-job-queue
spec:
  serviceName: postgres-headless
  replicas: 1   # can be 1 primary (or extend with replication later)
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgbouncer-users
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgbouncer-users
                  key: password
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_INITDB_ARGS
              value: "--auth=password"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
