apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: distributed-job-queue
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "admin"
  RABBITMQ_ERLANG_COOKIE: "changeme-erlang-cookie-32-chars-min"
