apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: distributed-job-queue
spec:
  type: NodePort
#  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      nodePort: 30672
    - name: management
      port: 15672
      nodePort: 31672
