apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: distributed-job-queue
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: epmd
      port: 4369
    - name: dist
      port: 25672
