apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: observability
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      serviceAccountName: fluentbit
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:3.1.4
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 2020
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlib
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: flb-state
              mountPath: /var/log/flb
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluentbit-config
        - name: varlib
          hostPath:
            path: /var/lib/docker/containers
        - name: flb-state
          hostPath:
            path: /var/log/flb
            type: DirectoryOrCreate
