apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # --- Namespace ---
  - namespace.yaml

  # --- Ingress ---
  - ingress/nginx-ingress.yaml

  # --- Migration (Job) ---
  - migration/job-migration.yaml

  # --- Postgres ---
  - postgres/statefulset-postgres.yaml
  - postgres/service-postgres.yaml
  - postgres/service-postgres-headless.yaml

  # --- PgBouncer ---
  - pgbouncer/deployment-pgbouncer.yaml
  - pgbouncer/service-pgbouncer.yaml
  - pgbouncer/configmap-pgbouncer.yaml
  - pgbouncer/secret-pgbouncer-users.yaml

  # --- RabbitMQ ---
  - rabbitmq/statefulset-rabbitmq.yaml
  - rabbitmq/service-rabbitmq.yaml
  - rabbitmq/service-rabbitmq-headless.yaml
  - rabbitmq/configmap-rabbitmq.yaml
  - rabbitmq/rabbitmq-conf.yaml
  - rabbitmq/rbac-rabbitmq.yaml
  - rabbitmq/secret-rabbitmq.yaml

  # --- Producer ---
  - producer/deployment-producer.yaml
  - producer/service-producer.yaml
