apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: distributed-job-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer
          ports:
            - containerPort: 6432
          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer
      volumes:
        - name: config
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: pgbouncer-config
              - secret:
                  name: pgbouncer-users