apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-users
  namespace: distributed-job-queue
type: Opaque
stringData:
  username: appuser
  password: apppass
  userlist.txt: |
    "appuser" "apppass"