apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/app/namespace
  - ../../base/app/postgres
  - ../../base/app/pgbouncer
  - ../../base/app/migration
  - ../../base/app/rabbitmq
  - ../../base/app/producer
  - ../../base/app/worker
  - ../../base/app/keda
  - ../../base/app/ingress
  - ../../base/observability
